### ISSUE TITLE
Comprehension Image doesn't match the code

### ISSUE THREAD

**Issue by abdulsattar** [learnyou/lysa#11]
Comprehension2.png on page 16 says `{ z : N | z > 2 }` when the corresponding code on Page 14 (2.9) says `{z : N | z >= 3}`

**Comment by pharpend** [comment]
On Thu, Jul 09, 2015 at 08:31:51AM -0700, Abdulsattar Mohammed wrote:

> Comprehension2.png on page 16 says `{ z : N | z > 2 }` when the
> corresponding code on Page 14 (2.9) says `{z : N | z >= 3}`

Thanks, I'll edit the graphic. For the record, the two types are
identical =p.
