### ISSUE TITLE
Eqn 2.11: Introduction of logical operators may be confusing

### ISSUE THREAD

**Issue by wei2912** [learnyou/lysa#8]
It seems that logical operators have not been introduced earlier in the text. Readers might be more familiar with using words such as "and" instead of the symbols introduced. The introduction of such symbols feel "incomplete" to me, since the logical-and operator was covered in passing, and other symbols are neglected.

**Comment by pharpend** [comment]
On Tue, Jul 07, 2015 at 08:28:30AM -0700, Ng Wei En wrote:

> It seems that logical operators have not been introduced earlier in
> the text. Readers might be more familiar with using words such as
> "and" instead of the symbols introduced. The introduction of such
> symbols feel "incomplete" to me, since the logical-and operator was
> covered in passing, and other symbols are neglected.

I agree. I removed all of the instances of `\land` in the chapter text,
and replaced them with `\text{ and }`. There are still instances of
`\land` in the appendices, but we'll deal with those later.

**Comment by pharpend** [comment]
I accidentally globbed this change in with ea671a6. Nonethess, this is fixed for now.
